#!/bin/bash
set -e
# Publish Dev version:  sh scripts/publish
# Publish specific version:  sh scripts/publish <version>
# Publish specific version & latest:  sh scripts/publish <version> true

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

git_semver_tag_resource_dir=$(cd $(dirname $0)/.. && pwd)

if not_installed docker; then
  echo "# docker is not installed! run the following commands:"
  echo "    brew install docker"
  echo "    brew cask install docker-machine"
  echo "    docker-machine create dev --driver virtualbox"
  echo '    eval $(docker-machine env dev)'
  echo "    docker login"
  exit 1
fi
name=johnharvey/concourse-git-semver-tag-resource
cd $git_semver_tag_resource_dir
latest=$2
if [ "$latest" == true  ]; then
  docker build . -t $name:${1:-dev} -t $name:latest
  docker push $name
else
  docker build . -t $name:${1:-dev}
  docker push $name:${1:-dev}
fi
